<a href="https://colab.research.google.com/github/LuchoGabba/Deep-Learning/blob/main/PyTorch.ipynb"> <img src='https://colab.research.google.com/assets/colab-badge.svg' /> </a>

# ![](https://images.g2crowd.com/uploads/product/image/social_landscape/social_landscape_656e174b12c49be1cfb4723a938ea43e/pytorch.png)

## Tensores de PyTorch

Los tensores son objetos de la clase ``torch.Tensor``.

In [1]:
import torch
import math

### Create a tensor

With 3 rows and 4 columns:

In [2]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[6.9780e+22, 7.2251e+28, 1.7841e+25, 1.8492e+20],
        [1.8494e+31, 4.7364e+30, 3.0386e+29, 1.9635e+17],
        [1.5621e+07, 7.6590e+28, 1.8492e+20, 9.2851e-04]])


Check this link about randomness: https://pytorch.org/docs/stable/notes/randomness.html

In [3]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


### Tensor shape

``torch.*_like()``


In [4]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[-5.5744e+17,  4.4842e-41, -1.6165e-27],
         [ 3.3134e-41,  4.4842e-44,  0.0000e+00]],

        [[ 8.9683e-44,  0.0000e+00,  1.8334e+14],
         [ 3.3127e-41,  0.0000e+00,  0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[-5.5744e+17,  4.4842e-41, -5.5744e+17],
         [ 4.4842e-41,  4.4842e-44,  0.0000e+00]],

        [[ 1.1210e-43,  0.0000e+00,  1.8334e+14],
         [ 3.3127e-41,  0.0000e+00,  0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.2332, 0.4047, 0.2162],
         [0.9927, 0.4128, 0.5938]],

        [[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]]])


### Data type of a tensor

By default is a float of 32 bits, but we can change de dtype

In [5]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[10.8626,  2.1505, 19.6913],
        [ 0.9956,  1.4148,  5.8364]], dtype=torch.float64)
tensor([[10,  2, 19],
        [ 0,  1,  5]], dtype=torch.int32)


Data type:

-  ``torch.bool``
-  ``torch.int8``
-  ``torch.uint8``
-  ``torch.int16``
-  ``torch.int32``
-  ``torch.int64``
-  ``torch.half``
-  ``torch.float``
-  ``torch.double``
-  ``torch.bfloat``

Check Broadcasting: https://pytorch.org/docs/stable/notes/broadcasting.html

Mathematical operations: https://pytorch.org/docs/stable/torch.html#math-operations

If you use '_' for mathematical operations, the tensor changes with the mathematical function.

To copy a tensor use ``clone()``

### Change dimensions

``unsqueeze()`` adds a new dimension of extension 1.

We can ``squeeze()`` only over dimensions of size 1.

Both methods work with '_'.

See: <https://pytorch.org/docs/stable/torch.html#torch.reshape>